name: FiapXApi - CICD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CI: true

jobs:
  code-analysis:
    name: 'Analyze Code'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.13'
      - name: Install Dependencies
        run: npm install
      - name: ESLint
        run: npm run lint:check
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.13'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
  test-unit:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    needs: [build, code-analysis]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.13'
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test:cov
  test-integration:
    name: 'Run Integration Tests'
    runs-on: ubuntu-latest
    needs: [test-unit]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.13'
      - name: Start Docker Dependencies
        run: docker compose up -d
      - name: Install Dependencies
        run: npm install
      - name: 'Wait 30s'
        run: sleep 30
      - name: Run Tests
        run: npm run test:integration:cov
      - name: Teardown
        run: docker compose down -v
  test-acceptance:
    name: 'Run Acceptance Tests'
    runs-on: ubuntu-latest
    needs: [test-unit]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.13'
      - name: Start Acceptance Tests Environment
        run: docker compose -f localstack/docker-compose.acceptance.yaml up -d
      - name: Install dependencies
        run: npm install
      - name: 'Wait 30s'
        run: sleep 30
      - name: Run Tests
        run: npm run test:acceptance
      - name: Teardown
        run: docker compose down -v
  build-container:
    name: 'Build Application Container'
    runs-on: ubuntu-latest
    needs: [test-acceptance, test-integration]
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    timeout-minutes: 10
    steps:
      - name: Configure Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            target=fiap-x-api
          tags: |
            thallisandre439/fiap-x-api:latest
            thallisandre439/fiap-x-api:v${{ github.run_number }}
  deploy:
    name: 'Deploy Application'
    runs-on: ubuntu-latest
    needs: [build-container]
    environment: 'production'
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure Kubectl
        run: aws eks update-kubeconfig --name fiap-x-k8s

      - name: Apply K8S
        run: |
          kubectl apply -f k8s/app.deployment.yaml
          kubectl rollout restart deployment/fiap-x-api
